version: "3.3"

services:
  db:
    container_name: androidbdd
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foot
      MYSQL_USER: user
      MYSQL_PASSWORD: root
